name: demo0314
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fair:
    path: ../fair/fair
  flutter:
    sdk: flutter
  args: ^1.5.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^1.4.0
  fair_compiler:
    path: ../fair/compiler
  flutter_test:
    sdk: flutter

# switch "fair_version" according to the local Flutter SDK version
dependency_overrides:
  fair_version:
    path: ../fair/flutter_version/flutter_2_0_6

flutter:
  assets:
    - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
